FROM scratch
ARG PROJECT_NAME="git-synchronizer"
ARG TARGETPLATFORM
ENV PROJECT_NAME=${PROJECT_NAME}
COPY $TARGETPLATFORM/${PROJECT_NAME} /
WORKDIR /
# hadolint ignore=DL3025
ENTRYPOINT ${PROJECT_NAME}
